#!/usr/bin/env ruby
# frozen_string_literal: true

# Handle shell errors (Ctrl+C / broken pipes) ----------------------------------
# borrowed from https://github.com/chocolateboy/cli-pasta
Signal.trap('INT', 'SYSTEM_DEFAULT') if Signal.list.include?('INT')
Signal.trap('PIPE', 'SYSTEM_DEFAULT') if Signal.list.include?('PIPE')

# Parse opts -------------------------------------------------------------------

require 'optparse'

parser = OptionParser.new do |opts|
  opts.banner = <<~BANNER
    Usage: cram append:zhuyin [<options>] <file>
    For each line of a given input CSV,
    take the Chinese character in the first field
    and append its Zhuyin transcription.

    With no <file> (or when <file> is -), read standard input.

    Supports Traditional Chinese characters only.
    Zhuyin table adapted from https://github.com/g0v/moedict-data.

  BANNER

  opts.on(
    '-d=DELIMITER', '--delimiter=DELIMITER',
    'specify the CSV column separator (default: ,)'
  )

  opts.on(
    '--[no-]strict',
    'abort on unexpected input or when lookup fails (default: on)',
    '(--no-strict: append an empty field)'
  )
end

begin
  params = { delimiter: ',', strict: true }
  parser.parse!(into: params)
rescue OptionParser::ParseError => e
  warn(e.message)
  warn(parser.help)
  exit 1
end

# Core logic -------------------------------------------------------------------

require 'csv'
require 'pathname'
require 'yaml'

DATA_DIR = Pathname.new(__dir__).join('../../../share/cram').freeze
ZHUYIN_TABLE = YAML.safe_load(File.read(DATA_DIR.join('zh/tw/zhuyin.yml'))).freeze

CSV.filter(col_sep: params[:delimiter]) do |row|
  raise "unexpected value: #{row.first}" if params[:strict] && !ZHUYIN_TABLE.key?(row.first)

  row << ZHUYIN_TABLE[row.first]
rescue => e
  # no-op if e.message !~ /@ rb_sysopen -/
  warn(e.message.split(' @ rb_sysopen - ').reverse.join(': '))
  exit 1
end
